replicaCount: 1

image:
  repository: gcr.io/btcw-development/go-websocket
  tag: latest
  pullPolicy: ifNotPresent

namespace: default

apps:
  go-websocket:
    name: go-websocket
    container:
      image: gcr.io/btcw-development/go-websocket
      tag: latest
      imagePullPolicy: ifNotPresent
    port: 8080
    resources:
      limits:
        cpu: 512m
        memory: 1Gi
      requests:
        cpu: 256m
        memory: 512Mi
    service:
      type: ClusterIP
      port: 8080


service:
  type: ClusterIP
  port: 8080

env:
  GIN_MODE: release

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
