# Go WebSocket Config Map Configuration
# Author: github@adhxabre
# ---
# This Configuration might not working properly on your
# system, so feel free to modify it following your configuration

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-websocket.name" . }}
  labels:
    app: {{ include "go-websocket.name" . }}
    chart: {{ include "go-websocket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  GIN_MODE: "release"
