# Go WebSocket Service Configuration
# Author: github@adhxabre
# ---
# This Configuration might not working properly on your
# system, so feel free to modify it following your configuration

apiVersion: v1
kind: Service
metadata:
  name: { { include "go-websocket.fullname" . } }
  labels:
    app: { { include "go-websocket.name" . } }
    chart: { { include "go-websocket.chart" . } }
    release: { { .Release.Name } }
    heritage: { { .Release.Service } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8080
      protocol: TCP
      name: HTTP
  selector:
    app: { { include "go-websocket.name" . } }
    release: { { .Release.Name } }
